# Generated by Django 4.2.10 on 2024-02-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destinations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("weather", models.CharField(max_length=200)),
                ("district", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("map_link", models.URLField()),
                ("image", models.ImageField(upload_to="images")),
                ("description", models.TextField()),
            ],
        ),
    ]
